kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: busybox-test
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-test
  template:
    metadata:
      labels:
        app: busybox-test
    spec:
      containers:
        - name: busybox
          image: busybox:1.29
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "tail -f /dev/null" ]
          volumeMounts:
          - name: volume1
            mountPath: "/mnt/volume1"
      volumes:
      - name: volume1
        persistentVolumeClaim:
          claimName: busybox-test